name: Test Build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyInstaller
    
    - name: Test PyInstaller
      run: |
        pyinstaller --version
        python -c "import PyInstaller; print('PyInstaller OK')"
    
    - name: List files
      run: |
        ls -la
        ls -la *.spec
