name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test imports
      run: |
        python -c "import fastapi; print('FastAPI OK')"
        python -c "import uvicorn; print('Uvicorn OK')"
        python -c "import PyQt5; print('PyQt5 OK')"
        python -c "import pandas; print('Pandas OK')"
        python -c "import matplotlib; print('Matplotlib OK')"
        python -c "import dnspython; print('dnspython OK')"

    - name: Test backend imports
      run: |
        cd backend
        python -c "from main import app; print('Backend main OK')"
        python -c "from services.dns_service import DNSService; print('DNS Service OK')"

    - name: Test frontend imports
      run: |
        cd frontend
        python -c "from pyqt_app import MainWindow; print('Frontend main OK')"
